name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '13.10'
    - name: Install dependencies
      run: yarn
      env:
        CI: true
    - name: Run tests
      run: yarn test
      env:
        CI: true
